# Путь к данным
data_file: /Users/andrejkrylov/Desktop/projectmacro/macro_main_linked.xlsx

# Имя столбца даты в исходном файле (если не уверены — можно оставить "date" или пусто,
# приложение попытается найти колонку с датой автоматически, в т.ч. "Unnamed: 0")
date_column: date

# (опционально) лист в Excel
excel_sheet: ""

# Размер таблицы по умолчанию
table_page_size: 25

# Алиасы для колонок (как показывать в UI)
aliases:
  "GDP_growth_yoy": "Рост ВВП, % г/г"
  "CPI_inflation_yoy": "Инфляция, % г/г"
  "Unemployment_rate": "Безработица, %"
  "Interest_rate": "Ключевая ставка"
  "USDRUB": "USD/RUB"

# Единицы измерения для отображаемых имён (после алиаса)
units:
  "Рост ВВП, % г/г": "%"
  "Инфляция, % г/г": "%"
  "Безработица, %": "%"
  "Ключевая ставка": "%"
  "USD/RUB": "руб."

# Источник данных (будет показан под графиком)
source: "Источник: Собственные расчёты на основе файла пользователя"

# Как отображать дату «последнего обновления» (берётся из mtime файла)
last_updated_label: "Обновлено: {dt}"  # {dt} будет заменён на дату/время





